"""v4_notifications

Revision ID: bac76b6d6d90
Revises:
Create Date: 2026-05-26 14:00:09.172660

"""

from __future__ import annotations

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op


revision: str = "bac76b6d6d90"
down_revision: str | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "tags",
        sa.Column("slug", sa.String(length=40), nullable=False),
        sa.Column("label", sa.String(length=40), nullable=False),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("slug"),
    )
    with op.batch_alter_table("tags", schema=None) as batch_op:
        batch_op.create_index("ix_tags_slug", ["slug"], unique=True)

    op.create_table(
        "users",
        sa.Column("email", sa.String(length=254), nullable=False),
        sa.Column("hashed_password", sa.String(length=255), nullable=False),
        sa.Column("first_name", sa.String(length=80), nullable=False),
        sa.Column("last_name", sa.String(length=80), nullable=False),
        sa.Column("age", sa.SmallInteger(), nullable=False),
        sa.Column(
            "gender",
            sa.Enum(
                "male",
                "female",
                "other",
                "prefer_not_to_say",
                name="gender",
                native_enum=False,
                length=32,
            ),
            nullable=False,
        ),
        sa.Column("is_active", sa.Boolean(), nullable=False),
        sa.Column("failed_login_count", sa.SmallInteger(), nullable=False),
        sa.Column("locked_until", sa.DateTime(timezone=True), nullable=True),
        sa.Column("last_login_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("last_login_ip", sa.String(length=45), nullable=True),
        sa.Column("avatar_url", sa.String(length=500), nullable=True),
        sa.Column("bio", sa.String(length=500), nullable=True),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("users", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_users_email"), ["email"], unique=True)

    op.create_table(
        "blocks",
        sa.Column("actor_user_id", sa.Uuid(), nullable=False),
        sa.Column("target_user_id", sa.Uuid(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(["actor_user_id"], ["users.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["target_user_id"], ["users.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("actor_user_id", "target_user_id"),
    )
    with op.batch_alter_table("blocks", schema=None) as batch_op:
        batch_op.create_index("ix_blocks_target", ["target_user_id"], unique=False)

    op.create_table(
        "device_tokens",
        sa.Column("user_id", sa.Uuid(), nullable=False),
        sa.Column("token", sa.String(length=255), nullable=False),
        sa.Column(
            "platform",
            sa.Enum("ios", "android", "web", name="deviceplatform", native_enum=False, length=32),
            nullable=False,
        ),
        sa.Column("revoked_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("last_seen_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(["user_id"], ["users.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("token"),
    )
    with op.batch_alter_table("device_tokens", schema=None) as batch_op:
        batch_op.create_index("ix_device_tokens_token", ["token"], unique=True)
        batch_op.create_index("ix_device_tokens_user", ["user_id"], unique=False)

    op.create_table(
        "login_attempts",
        sa.Column("email", sa.String(length=254), nullable=False),
        sa.Column("attempted_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("success", sa.Boolean(), nullable=False),
        sa.Column("user_id", sa.Uuid(), nullable=True),
        sa.Column("ip", sa.String(length=45), nullable=True),
        sa.Column("user_agent", sa.String(length=255), nullable=True),
        sa.Column("reason", sa.String(length=64), nullable=True),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.ForeignKeyConstraint(["user_id"], ["users.id"], ondelete="SET NULL"),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("login_attempts", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_login_attempts_email"), ["email"], unique=False)
        batch_op.create_index(
            "ix_login_attempts_email_time", ["email", "attempted_at"], unique=False
        )
        batch_op.create_index("ix_login_attempts_user", ["user_id"], unique=False)

    op.create_table(
        "password_reset_tokens",
        sa.Column("user_id", sa.Uuid(), nullable=False),
        sa.Column("token_hash", sa.String(length=64), nullable=False),
        sa.Column("issued_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("expires_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("used_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.ForeignKeyConstraint(["user_id"], ["users.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("token_hash"),
    )
    with op.batch_alter_table("password_reset_tokens", schema=None) as batch_op:
        batch_op.create_index("ix_password_reset_tokens_hash", ["token_hash"], unique=True)
        batch_op.create_index("ix_password_reset_tokens_user", ["user_id"], unique=False)

    op.create_table(
        "refresh_tokens",
        sa.Column("user_id", sa.Uuid(), nullable=False),
        sa.Column("jti", sa.String(length=64), nullable=False),
        sa.Column("family_id", sa.Uuid(), nullable=False),
        sa.Column("issued_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("expires_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("user_agent", sa.String(length=255), nullable=True),
        sa.Column("ip", sa.String(length=45), nullable=True),
        sa.Column("revoked_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("replaced_by_jti", sa.String(length=64), nullable=True),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.ForeignKeyConstraint(["user_id"], ["users.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("refresh_tokens", schema=None) as batch_op:
        batch_op.create_index("ix_refresh_tokens_family", ["family_id"], unique=False)
        batch_op.create_index("ix_refresh_tokens_jti", ["jti"], unique=True)
        batch_op.create_index("ix_refresh_tokens_user", ["user_id"], unique=False)

    op.create_table(
        "reports",
        sa.Column("reporter_id", sa.Uuid(), nullable=False),
        sa.Column(
            "target_type",
            sa.Enum("user", "room", "message", name="reporttarget", native_enum=False, length=32),
            nullable=False,
        ),
        sa.Column("target_id", sa.Uuid(), nullable=False),
        sa.Column(
            "reason",
            sa.Enum(
                "spam",
                "harassment",
                "inappropriate",
                "fake_profile",
                "other",
                name="reportreason",
                native_enum=False,
                length=32,
            ),
            nullable=False,
        ),
        sa.Column("description", sa.String(length=1000), nullable=True),
        sa.Column(
            "status",
            sa.Enum(
                "pending",
                "reviewed",
                "dismissed",
                "actioned",
                name="reportstatus",
                native_enum=False,
                length=32,
            ),
            nullable=False,
        ),
        sa.Column("reviewed_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("reviewer_id", sa.Uuid(), nullable=True),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(["reporter_id"], ["users.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["reviewer_id"], ["users.id"], ondelete="SET NULL"),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("reports", schema=None) as batch_op:
        batch_op.create_index("ix_reports_reporter", ["reporter_id"], unique=False)
        batch_op.create_index("ix_reports_status", ["status"], unique=False)
        batch_op.create_index("ix_reports_target", ["target_type", "target_id"], unique=False)

    op.create_table(
        "rooms",
        sa.Column("owner_id", sa.Uuid(), nullable=False),
        sa.Column("name", sa.String(length=120), nullable=False),
        sa.Column(
            "purpose",
            sa.Enum(
                "play",
                "movie",
                "travel",
                "chat",
                "landmark",
                "custom",
                name="roompurpose",
                native_enum=False,
                length=32,
            ),
            nullable=False,
        ),
        sa.Column("latitude", sa.Float(), nullable=False),
        sa.Column("longitude", sa.Float(), nullable=False),
        sa.Column("radius_km", sa.Float(), nullable=False),
        sa.Column("custom_purpose", sa.String(length=60), nullable=True),
        sa.Column("max_members", sa.SmallInteger(), nullable=False),
        sa.Column(
            "visibility",
            sa.Enum("public", "private", "dm", name="roomvisibility", native_enum=False, length=32),
            nullable=False,
        ),
        sa.Column(
            "status",
            sa.Enum(
                "active", "archived", "deleted", name="roomstatus", native_enum=False, length=32
            ),
            nullable=False,
        ),
        sa.Column("invite_code", sa.String(length=24), nullable=True),
        sa.Column("expires_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("starts_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("ends_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("cover_photo_url", sa.String(length=500), nullable=True),
        sa.Column("description", sa.String(length=1000), nullable=True),
        sa.Column("deleted_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("restore_until", sa.DateTime(timezone=True), nullable=True),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.CheckConstraint("latitude BETWEEN -90 AND 90", name="ck_rooms_latitude"),
        sa.CheckConstraint("longitude BETWEEN -180 AND 180", name="ck_rooms_longitude"),
        sa.CheckConstraint("max_members > 0 AND max_members <= 500", name="ck_rooms_max_members"),
        sa.CheckConstraint("radius_km > 0 AND radius_km <= 200", name="ck_rooms_radius"),
        sa.ForeignKeyConstraint(["owner_id"], ["users.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("rooms", schema=None) as batch_op:
        batch_op.create_index("ix_rooms_ends_at", ["ends_at"], unique=False)
        batch_op.create_index("ix_rooms_invite_code", ["invite_code"], unique=True)
        batch_op.create_index("ix_rooms_owner", ["owner_id"], unique=False)
        batch_op.create_index(batch_op.f("ix_rooms_owner_id"), ["owner_id"], unique=False)
        batch_op.create_index("ix_rooms_starts_at", ["starts_at"], unique=False)
        batch_op.create_index(
            "ix_rooms_status_visibility_geo",
            ["status", "visibility", "latitude", "longitude"],
            unique=False,
        )

    op.create_table(
        "user_tags",
        sa.Column("user_id", sa.Uuid(), nullable=False),
        sa.Column("tag_id", sa.Uuid(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(["tag_id"], ["tags.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["user_id"], ["users.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("user_id", "tag_id"),
    )
    with op.batch_alter_table("user_tags", schema=None) as batch_op:
        batch_op.create_index("ix_user_tags_tag", ["tag_id"], unique=False)

    op.create_table(
        "messages",
        sa.Column("room_id", sa.Uuid(), nullable=False),
        sa.Column("sender_id", sa.Uuid(), nullable=False),
        sa.Column("body", sa.String(length=4000), nullable=False),
        sa.Column(
            "message_type",
            sa.Enum("text", "system", name="messagetype", native_enum=False, length=32),
            nullable=False,
        ),
        sa.Column("client_message_id", sa.String(length=64), nullable=True),
        sa.Column("parent_message_id", sa.Uuid(), nullable=True),
        sa.Column("edited_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("deleted_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("pinned_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("pinned_by_id", sa.Uuid(), nullable=True),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(["parent_message_id"], ["messages.id"], ondelete="SET NULL"),
        sa.ForeignKeyConstraint(["pinned_by_id"], ["users.id"], ondelete="SET NULL"),
        sa.ForeignKeyConstraint(["room_id"], ["rooms.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["sender_id"], ["users.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("messages", schema=None) as batch_op:
        batch_op.create_index(
            "ix_messages_idempotency",
            ["room_id", "sender_id", "client_message_id"],
            unique=True,
            sqlite_where=None,
        )
        batch_op.create_index("ix_messages_pinned", ["room_id", "pinned_at"], unique=False)
        batch_op.create_index("ix_messages_room_created", ["room_id", "created_at"], unique=False)
        batch_op.create_index(
            "ix_messages_room_id_created", ["room_id", "id", "created_at"], unique=False
        )
        batch_op.create_index("ix_messages_sender", ["sender_id"], unique=False)

    op.create_table(
        "room_details",
        sa.Column("room_id", sa.Uuid(), nullable=False),
        sa.Column("heading", sa.String(length=120), nullable=False),
        sa.Column("body", sa.String(length=2000), nullable=False),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(["room_id"], ["rooms.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("room_details", schema=None) as batch_op:
        batch_op.create_index("ix_room_details_room", ["room_id"], unique=False)

    op.create_table(
        "room_events",
        sa.Column("room_id", sa.Uuid(), nullable=False),
        sa.Column(
            "event_type",
            sa.Enum(
                "created",
                "updated",
                "archived",
                "reactivated",
                "deleted",
                "restored",
                "ownership_transferred",
                "member_joined",
                "member_left",
                "member_kicked",
                "member_promoted",
                "member_demoted",
                "waitlist_joined",
                "waitlist_promoted",
                name="roomeventtype",
                native_enum=False,
                length=32,
            ),
            nullable=False,
        ),
        sa.Column("actor_id", sa.Uuid(), nullable=True),
        sa.Column("target_user_id", sa.Uuid(), nullable=True),
        sa.Column("payload", sa.String(length=2000), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.ForeignKeyConstraint(["actor_id"], ["users.id"], ondelete="SET NULL"),
        sa.ForeignKeyConstraint(["room_id"], ["rooms.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["target_user_id"], ["users.id"], ondelete="SET NULL"),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("room_events", schema=None) as batch_op:
        batch_op.create_index(
            "ix_room_events_room_created", ["room_id", "created_at"], unique=False
        )
        batch_op.create_index("ix_room_events_type", ["event_type"], unique=False)

    op.create_table(
        "room_members",
        sa.Column("room_id", sa.Uuid(), nullable=False),
        sa.Column("user_id", sa.Uuid(), nullable=False),
        sa.Column(
            "role",
            sa.Enum("owner", "moderator", "member", name="roomrole", native_enum=False, length=32),
            nullable=False,
        ),
        sa.Column(
            "state",
            sa.Enum(
                "active",
                "waitlisted",
                "banned",
                name="membershipstate",
                native_enum=False,
                length=32,
            ),
            nullable=False,
        ),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(["room_id"], ["rooms.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["user_id"], ["users.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("room_id", "user_id"),
    )
    with op.batch_alter_table("room_members", schema=None) as batch_op:
        batch_op.create_index("ix_room_members_state", ["room_id", "state"], unique=False)
        batch_op.create_index("ix_room_members_user", ["user_id"], unique=False)

    op.create_table(
        "room_tags",
        sa.Column("room_id", sa.Uuid(), nullable=False),
        sa.Column("tag_id", sa.Uuid(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(["room_id"], ["rooms.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["tag_id"], ["tags.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("room_id", "tag_id"),
    )
    with op.batch_alter_table("room_tags", schema=None) as batch_op:
        batch_op.create_index("ix_room_tags_tag", ["tag_id"], unique=False)

    op.create_table(
        "saved_rooms",
        sa.Column("user_id", sa.Uuid(), nullable=False),
        sa.Column("room_id", sa.Uuid(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(["room_id"], ["rooms.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["user_id"], ["users.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("user_id", "room_id"),
    )
    with op.batch_alter_table("saved_rooms", schema=None) as batch_op:
        batch_op.create_index("ix_saved_rooms_user", ["user_id"], unique=False)

    op.create_table(
        "message_reactions",
        sa.Column("message_id", sa.Uuid(), nullable=False),
        sa.Column("user_id", sa.Uuid(), nullable=False),
        sa.Column("emoji", sa.String(length=16), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(["message_id"], ["messages.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["user_id"], ["users.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("message_id", "user_id", "emoji"),
        sa.UniqueConstraint("message_id", "user_id", "emoji", name="uq_message_reactions"),
    )
    with op.batch_alter_table("message_reactions", schema=None) as batch_op:
        batch_op.create_index("ix_message_reactions_user", ["user_id"], unique=False)

    op.create_table(
        "notifications",
        sa.Column("user_id", sa.Uuid(), nullable=False),
        sa.Column(
            "type",
            sa.Enum(
                "mention",
                "reaction",
                "reply",
                "dm_message",
                "room_kicked",
                "room_promoted",
                "room_demoted",
                "waitlist_promoted",
                "ownership_transferred",
                "room_archived",
                "room_deleted",
                name="notificationtype",
                native_enum=False,
                length=32,
            ),
            nullable=False,
        ),
        sa.Column("actor_id", sa.Uuid(), nullable=True),
        sa.Column("room_id", sa.Uuid(), nullable=True),
        sa.Column("message_id", sa.Uuid(), nullable=True),
        sa.Column("payload", sa.JSON(), nullable=True),
        sa.Column("read_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(["actor_id"], ["users.id"], ondelete="SET NULL"),
        sa.ForeignKeyConstraint(["message_id"], ["messages.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["room_id"], ["rooms.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["user_id"], ["users.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("notifications", schema=None) as batch_op:
        batch_op.create_index(
            "ix_notifications_user_created", ["user_id", "created_at"], unique=False
        )
        batch_op.create_index("ix_notifications_user_unread", ["user_id", "read_at"], unique=False)

    op.create_table(
        "room_read_states",
        sa.Column("room_id", sa.Uuid(), nullable=False),
        sa.Column("user_id", sa.Uuid(), nullable=False),
        sa.Column("last_read_message_id", sa.Uuid(), nullable=True),
        sa.Column("last_read_at", sa.DateTime(timezone=True), nullable=True),
        sa.ForeignKeyConstraint(["last_read_message_id"], ["messages.id"], ondelete="SET NULL"),
        sa.ForeignKeyConstraint(["room_id"], ["rooms.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["user_id"], ["users.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("room_id", "user_id"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("room_read_states")
    with op.batch_alter_table("notifications", schema=None) as batch_op:
        batch_op.drop_index("ix_notifications_user_unread")
        batch_op.drop_index("ix_notifications_user_created")

    op.drop_table("notifications")
    with op.batch_alter_table("message_reactions", schema=None) as batch_op:
        batch_op.drop_index("ix_message_reactions_user")

    op.drop_table("message_reactions")
    with op.batch_alter_table("saved_rooms", schema=None) as batch_op:
        batch_op.drop_index("ix_saved_rooms_user")

    op.drop_table("saved_rooms")
    with op.batch_alter_table("room_tags", schema=None) as batch_op:
        batch_op.drop_index("ix_room_tags_tag")

    op.drop_table("room_tags")
    with op.batch_alter_table("room_members", schema=None) as batch_op:
        batch_op.drop_index("ix_room_members_user")
        batch_op.drop_index("ix_room_members_state")

    op.drop_table("room_members")
    with op.batch_alter_table("room_events", schema=None) as batch_op:
        batch_op.drop_index("ix_room_events_type")
        batch_op.drop_index("ix_room_events_room_created")

    op.drop_table("room_events")
    with op.batch_alter_table("room_details", schema=None) as batch_op:
        batch_op.drop_index("ix_room_details_room")

    op.drop_table("room_details")
    with op.batch_alter_table("messages", schema=None) as batch_op:
        batch_op.drop_index("ix_messages_sender")
        batch_op.drop_index("ix_messages_room_id_created")
        batch_op.drop_index("ix_messages_room_created")
        batch_op.drop_index("ix_messages_pinned")
        batch_op.drop_index("ix_messages_idempotency", sqlite_where=None)

    op.drop_table("messages")
    with op.batch_alter_table("user_tags", schema=None) as batch_op:
        batch_op.drop_index("ix_user_tags_tag")

    op.drop_table("user_tags")
    with op.batch_alter_table("rooms", schema=None) as batch_op:
        batch_op.drop_index("ix_rooms_status_visibility_geo")
        batch_op.drop_index("ix_rooms_starts_at")
        batch_op.drop_index(batch_op.f("ix_rooms_owner_id"))
        batch_op.drop_index("ix_rooms_owner")
        batch_op.drop_index("ix_rooms_invite_code")
        batch_op.drop_index("ix_rooms_ends_at")

    op.drop_table("rooms")
    with op.batch_alter_table("reports", schema=None) as batch_op:
        batch_op.drop_index("ix_reports_target")
        batch_op.drop_index("ix_reports_status")
        batch_op.drop_index("ix_reports_reporter")

    op.drop_table("reports")
    with op.batch_alter_table("refresh_tokens", schema=None) as batch_op:
        batch_op.drop_index("ix_refresh_tokens_user")
        batch_op.drop_index("ix_refresh_tokens_jti")
        batch_op.drop_index("ix_refresh_tokens_family")

    op.drop_table("refresh_tokens")
    with op.batch_alter_table("password_reset_tokens", schema=None) as batch_op:
        batch_op.drop_index("ix_password_reset_tokens_user")
        batch_op.drop_index("ix_password_reset_tokens_hash")

    op.drop_table("password_reset_tokens")
    with op.batch_alter_table("login_attempts", schema=None) as batch_op:
        batch_op.drop_index("ix_login_attempts_user")
        batch_op.drop_index("ix_login_attempts_email_time")
        batch_op.drop_index(batch_op.f("ix_login_attempts_email"))

    op.drop_table("login_attempts")
    with op.batch_alter_table("device_tokens", schema=None) as batch_op:
        batch_op.drop_index("ix_device_tokens_user")
        batch_op.drop_index("ix_device_tokens_token")

    op.drop_table("device_tokens")
    with op.batch_alter_table("blocks", schema=None) as batch_op:
        batch_op.drop_index("ix_blocks_target")

    op.drop_table("blocks")
    with op.batch_alter_table("users", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_users_email"))

    op.drop_table("users")
    with op.batch_alter_table("tags", schema=None) as batch_op:
        batch_op.drop_index("ix_tags_slug")

    op.drop_table("tags")
    # ### end Alembic commands ###
