"""chat_v2_reactions_edits_read_state_pin

Revision ID: a87fb929a095
Revises:
Create Date: 2026-05-26 13:01:17.313259

"""

from __future__ import annotations

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op


revision: str = "a87fb929a095"
down_revision: str | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "users",
        sa.Column("email", sa.String(length=254), nullable=False),
        sa.Column("hashed_password", sa.String(length=255), nullable=False),
        sa.Column("first_name", sa.String(length=80), nullable=False),
        sa.Column("last_name", sa.String(length=80), nullable=False),
        sa.Column("age", sa.SmallInteger(), nullable=False),
        sa.Column(
            "gender",
            sa.Enum(
                "male",
                "female",
                "other",
                "prefer_not_to_say",
                name="gender",
                native_enum=False,
                length=32,
            ),
            nullable=False,
        ),
        sa.Column("is_active", sa.Boolean(), nullable=False),
        sa.Column("failed_login_count", sa.SmallInteger(), nullable=False),
        sa.Column("locked_until", sa.DateTime(timezone=True), nullable=True),
        sa.Column("last_login_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("last_login_ip", sa.String(length=45), nullable=True),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("users", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_users_email"), ["email"], unique=True)

    op.create_table(
        "login_attempts",
        sa.Column("email", sa.String(length=254), nullable=False),
        sa.Column("attempted_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("success", sa.Boolean(), nullable=False),
        sa.Column("user_id", sa.Uuid(), nullable=True),
        sa.Column("ip", sa.String(length=45), nullable=True),
        sa.Column("user_agent", sa.String(length=255), nullable=True),
        sa.Column("reason", sa.String(length=64), nullable=True),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.ForeignKeyConstraint(["user_id"], ["users.id"], ondelete="SET NULL"),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("login_attempts", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_login_attempts_email"), ["email"], unique=False)
        batch_op.create_index(
            "ix_login_attempts_email_time", ["email", "attempted_at"], unique=False
        )
        batch_op.create_index("ix_login_attempts_user", ["user_id"], unique=False)

    op.create_table(
        "password_reset_tokens",
        sa.Column("user_id", sa.Uuid(), nullable=False),
        sa.Column("token_hash", sa.String(length=64), nullable=False),
        sa.Column("issued_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("expires_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("used_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.ForeignKeyConstraint(["user_id"], ["users.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("token_hash"),
    )
    with op.batch_alter_table("password_reset_tokens", schema=None) as batch_op:
        batch_op.create_index("ix_password_reset_tokens_hash", ["token_hash"], unique=True)
        batch_op.create_index("ix_password_reset_tokens_user", ["user_id"], unique=False)

    op.create_table(
        "refresh_tokens",
        sa.Column("user_id", sa.Uuid(), nullable=False),
        sa.Column("jti", sa.String(length=64), nullable=False),
        sa.Column("family_id", sa.Uuid(), nullable=False),
        sa.Column("issued_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("expires_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("user_agent", sa.String(length=255), nullable=True),
        sa.Column("ip", sa.String(length=45), nullable=True),
        sa.Column("revoked_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("replaced_by_jti", sa.String(length=64), nullable=True),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.ForeignKeyConstraint(["user_id"], ["users.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("refresh_tokens", schema=None) as batch_op:
        batch_op.create_index("ix_refresh_tokens_family", ["family_id"], unique=False)
        batch_op.create_index("ix_refresh_tokens_jti", ["jti"], unique=True)
        batch_op.create_index("ix_refresh_tokens_user", ["user_id"], unique=False)

    op.create_table(
        "rooms",
        sa.Column("owner_id", sa.Uuid(), nullable=False),
        sa.Column("name", sa.String(length=120), nullable=False),
        sa.Column(
            "purpose",
            sa.Enum(
                "play",
                "movie",
                "travel",
                "chat",
                "landmark",
                "custom",
                name="roompurpose",
                native_enum=False,
                length=32,
            ),
            nullable=False,
        ),
        sa.Column("latitude", sa.Float(), nullable=False),
        sa.Column("longitude", sa.Float(), nullable=False),
        sa.Column("radius_km", sa.Float(), nullable=False),
        sa.Column("custom_purpose", sa.String(length=60), nullable=True),
        sa.Column("max_members", sa.SmallInteger(), nullable=False),
        sa.Column(
            "visibility",
            sa.Enum("public", "private", name="roomvisibility", native_enum=False, length=32),
            nullable=False,
        ),
        sa.Column(
            "status",
            sa.Enum(
                "active", "archived", "deleted", name="roomstatus", native_enum=False, length=32
            ),
            nullable=False,
        ),
        sa.Column("invite_code", sa.String(length=24), nullable=True),
        sa.Column("expires_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.CheckConstraint("latitude BETWEEN -90 AND 90", name="ck_rooms_latitude"),
        sa.CheckConstraint("longitude BETWEEN -180 AND 180", name="ck_rooms_longitude"),
        sa.CheckConstraint("max_members > 0 AND max_members <= 500", name="ck_rooms_max_members"),
        sa.CheckConstraint("radius_km > 0 AND radius_km <= 200", name="ck_rooms_radius"),
        sa.ForeignKeyConstraint(["owner_id"], ["users.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("rooms", schema=None) as batch_op:
        batch_op.create_index("ix_rooms_invite_code", ["invite_code"], unique=True)
        batch_op.create_index("ix_rooms_owner", ["owner_id"], unique=False)
        batch_op.create_index(batch_op.f("ix_rooms_owner_id"), ["owner_id"], unique=False)
        batch_op.create_index(
            "ix_rooms_status_visibility_geo",
            ["status", "visibility", "latitude", "longitude"],
            unique=False,
        )

    op.create_table(
        "messages",
        sa.Column("room_id", sa.Uuid(), nullable=False),
        sa.Column("sender_id", sa.Uuid(), nullable=False),
        sa.Column("body", sa.String(length=4000), nullable=False),
        sa.Column(
            "message_type",
            sa.Enum("text", "system", name="messagetype", native_enum=False, length=32),
            nullable=False,
        ),
        sa.Column("client_message_id", sa.String(length=64), nullable=True),
        sa.Column("parent_message_id", sa.Uuid(), nullable=True),
        sa.Column("edited_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("deleted_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("pinned_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("pinned_by_id", sa.Uuid(), nullable=True),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(["parent_message_id"], ["messages.id"], ondelete="SET NULL"),
        sa.ForeignKeyConstraint(["pinned_by_id"], ["users.id"], ondelete="SET NULL"),
        sa.ForeignKeyConstraint(["room_id"], ["rooms.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["sender_id"], ["users.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("messages", schema=None) as batch_op:
        batch_op.create_index(
            "ix_messages_idempotency",
            ["room_id", "sender_id", "client_message_id"],
            unique=True,
            sqlite_where=None,
        )
        batch_op.create_index("ix_messages_pinned", ["room_id", "pinned_at"], unique=False)
        batch_op.create_index("ix_messages_room_created", ["room_id", "created_at"], unique=False)
        batch_op.create_index(
            "ix_messages_room_id_created", ["room_id", "id", "created_at"], unique=False
        )
        batch_op.create_index("ix_messages_sender", ["sender_id"], unique=False)

    op.create_table(
        "room_details",
        sa.Column("room_id", sa.Uuid(), nullable=False),
        sa.Column("heading", sa.String(length=120), nullable=False),
        sa.Column("body", sa.String(length=2000), nullable=False),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(["room_id"], ["rooms.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("room_details", schema=None) as batch_op:
        batch_op.create_index("ix_room_details_room", ["room_id"], unique=False)

    op.create_table(
        "room_members",
        sa.Column("room_id", sa.Uuid(), nullable=False),
        sa.Column("user_id", sa.Uuid(), nullable=False),
        sa.Column(
            "role",
            sa.Enum("owner", "member", name="roomrole", native_enum=False, length=32),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(["room_id"], ["rooms.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["user_id"], ["users.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("room_id", "user_id"),
    )
    with op.batch_alter_table("room_members", schema=None) as batch_op:
        batch_op.create_index("ix_room_members_user", ["user_id"], unique=False)

    op.create_table(
        "message_reactions",
        sa.Column("message_id", sa.Uuid(), nullable=False),
        sa.Column("user_id", sa.Uuid(), nullable=False),
        sa.Column("emoji", sa.String(length=16), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(["message_id"], ["messages.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["user_id"], ["users.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("message_id", "user_id", "emoji"),
        sa.UniqueConstraint("message_id", "user_id", "emoji", name="uq_message_reactions"),
    )
    with op.batch_alter_table("message_reactions", schema=None) as batch_op:
        batch_op.create_index("ix_message_reactions_user", ["user_id"], unique=False)

    op.create_table(
        "room_read_states",
        sa.Column("room_id", sa.Uuid(), nullable=False),
        sa.Column("user_id", sa.Uuid(), nullable=False),
        sa.Column("last_read_message_id", sa.Uuid(), nullable=True),
        sa.Column("last_read_at", sa.DateTime(timezone=True), nullable=True),
        sa.ForeignKeyConstraint(["last_read_message_id"], ["messages.id"], ondelete="SET NULL"),
        sa.ForeignKeyConstraint(["room_id"], ["rooms.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["user_id"], ["users.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("room_id", "user_id"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("room_read_states")
    with op.batch_alter_table("message_reactions", schema=None) as batch_op:
        batch_op.drop_index("ix_message_reactions_user")

    op.drop_table("message_reactions")
    with op.batch_alter_table("room_members", schema=None) as batch_op:
        batch_op.drop_index("ix_room_members_user")

    op.drop_table("room_members")
    with op.batch_alter_table("room_details", schema=None) as batch_op:
        batch_op.drop_index("ix_room_details_room")

    op.drop_table("room_details")
    with op.batch_alter_table("messages", schema=None) as batch_op:
        batch_op.drop_index("ix_messages_sender")
        batch_op.drop_index("ix_messages_room_id_created")
        batch_op.drop_index("ix_messages_room_created")
        batch_op.drop_index("ix_messages_pinned")
        batch_op.drop_index("ix_messages_idempotency", sqlite_where=None)

    op.drop_table("messages")
    with op.batch_alter_table("rooms", schema=None) as batch_op:
        batch_op.drop_index("ix_rooms_status_visibility_geo")
        batch_op.drop_index(batch_op.f("ix_rooms_owner_id"))
        batch_op.drop_index("ix_rooms_owner")
        batch_op.drop_index("ix_rooms_invite_code")

    op.drop_table("rooms")
    with op.batch_alter_table("refresh_tokens", schema=None) as batch_op:
        batch_op.drop_index("ix_refresh_tokens_user")
        batch_op.drop_index("ix_refresh_tokens_jti")
        batch_op.drop_index("ix_refresh_tokens_family")

    op.drop_table("refresh_tokens")
    with op.batch_alter_table("password_reset_tokens", schema=None) as batch_op:
        batch_op.drop_index("ix_password_reset_tokens_user")
        batch_op.drop_index("ix_password_reset_tokens_hash")

    op.drop_table("password_reset_tokens")
    with op.batch_alter_table("login_attempts", schema=None) as batch_op:
        batch_op.drop_index("ix_login_attempts_user")
        batch_op.drop_index("ix_login_attempts_email_time")
        batch_op.drop_index(batch_op.f("ix_login_attempts_email"))

    op.drop_table("login_attempts")
    with op.batch_alter_table("users", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_users_email"))

    op.drop_table("users")
    # ### end Alembic commands ###
